### ISSUE TITLE
Task if or a Hybrid setup instead of cloud-only

### ISSUE THREAD

**Issue by rschouten97** [Tools4everBV/HelloID-Conn-SA-Full-Exchange-Online-SharedMailboxCreate#1]
The task for this delegated form creates a mailbox in Exchange Online, but then also creates a local AD group to assign the permissions to.
This is a hybrid setup instead of cloud-only and should be changed accordingly or renamed to indicate the hybrid setup.

**Comment by rhouthuijzen** [comment]
Fixed in new PR
